import {FeeFormData, SelectOption} from "@/types/fee.types";

export const CURRENCY_OPTIONS: SelectOption[] = [
    { label: "Select Currency", value: "" },
    { label: "NGN - Nigerian Naira", value: "NGN" },
    { label: "USD - US Dollar", value: "USD" },
    { label: "EUR - Euro", value: "EUR" },
    { label: "GHS - Ghanaian Cedi", value: "GHS" },
    { label: "KES - Kenyan Shilling", value: "KES" },
    { label: "ZAR - South African Rand", value: "ZAR" },
    { label: "USDT - Crypto", value: "USDT" },
    { label: "DZD - Algerian Dinar", value: "DZD" },
    { label: "AOA - Angolan Kwanza", value: "AOA" },
    { label: "XOF - CFA Franc BCEAO", value: "XOF" },
    { label: "BWP - Botswana Pula", value: "BWP" },
    { label: "BIF - Burundian Franc", value: "BIF" },
    { label: "CVE - Cape Verdean Escudo", value: "CVE" },
    { label: "XAF - CFA Franc BEAC", value: "XAF" },
    { label: "KMF - Comorian Franc", value: "KMF" },
    { label: "DJF - Djiboutian Franc", value: "DJF" },
    { label: "EGP - Egyptian Pound", value: "EGP" },
    { label: "ERN - Eritrean Nakfa", value: "ERN" },
    { label: "SZL - Eswatini Lilangeni", value: "SZL" },
    { label: "ETB - Ethiopian Birr", value: "ETB" },
    { label: "GMD - Gambian Dalasi", value: "GMD" },
    { label: "GNF - Guinean Franc", value: "GNF" },
    { label: "LSL - Lesotho Loti", value: "LSL" },
    { label: "LRD - Liberian Dollar", value: "LRD" },
    { label: "LYD - Libyan Dinar", value: "LYD" },
    { label: "MWK - Malawian Kwacha", value: "MWK" },
    { label: "MGA - Malagasy Ariary", value: "MGA" },
    { label: "MRU - Mauritanian Ouguiya", value: "MRU" },
    { label: "MUR - Mauritian Rupee", value: "MUR" },
    { label: "MAD - Moroccan Dirham", value: "MAD" },
    { label: "MZN - Mozambican Metical", value: "MZN" },
    { label: "NAD - Namibian Dollar", value: "NAD" },
    { label: "RWF - Rwandan Franc", value: "RWF" },
    { label: "STD - São Tomé and Príncipe Dobra", value: "STD" },
    { label: "SCR - Seychellois Rupee", value: "SCR" },
    { label: "SLL - Sierra Leonean Leone", value: "SLL" },
    { label: "SOS - Somali Shilling", value: "SOS" },
    { label: "SSP - South Sudanese Pound", value: "SSP" },
    { label: "SDG - Sudanese Pound", value: "SDG" },
    { label: "TZS - Tanzanian Shilling", value: "TZS" },
    { label: "TND - Tunisian Dinar", value: "TND" },
    { label: "UGX - Ugandan Shilling", value: "UGX" },
    { label: "ZMW - Zambian Kwacha", value: "ZMW" },
    { label: "ZWL - Zimbabwean Dollar", value: "ZWL" },
];

export const PAYMENT_METHOD_OPTIONS: SelectOption[] = [
    { label: "Select Payment Method", value: "" },
    { label: "Dedicated Account", value: "dedicated" },
    { label: "Bank Transfer", value: "BANKTRANSFER" },
    { label: "USSD", value: "USSD" },
    { label: "Pay with Bank", value: "PAYWITHBANK" },
    { label: "Pay with Phone", value: "PAYWITHPHONE" },
];

export const FEE_TYPE_OPTIONS: SelectOption[] = [
    { label: "Select Fee Type", value: "" },
    { label: "Percentage (%)", value: "percent" },
    { label: "Flat Amount", value: "flat" },
];

export const INITIAL_FEE_FORM: FeeFormData = {
    currency: "",
    fee_type: "",
    fee: "",
    fee_cap: "",
    range_set: "",
    min_fee: "",
    max_fee: "",
};
