import * as CountryFlags from 'country-flag-icons/react/3x2'
import { COUNTRYDATA } from '@/helpers/countryCodes';
interface CountryFlagProps {
    countryName: string;
}

export default function CountryFlag({ currencyCode }: { currencyCode: any }) {
    // Map the country code to the country name

    let countryName: string = ''
    if (currencyCode) {
        if (currencyCode.length == 3) {
            countryName = COUNTRYDATA.find((item: any) => item.currencyCode == currencyCode.toUpperCase())?.isoName || ''
        } else {
            countryName = currencyCode
        }
    }

    const className = 'w-[1.9rem]'

    const countryFlagComponents: any = {
        AC: <CountryFlags.AC title="Ascension Island" className={className} />,
        AD: <CountryFlags.AD title="Andorra" className={className} />,
        AE: <CountryFlags.AE title="United Arab Emirates" className={className} />,
        AF: <CountryFlags.AF title="Afghanistan" className={className} />,
        AG: <CountryFlags.AG title="Antigua and Barbuda" className={className} />,
        AI: <CountryFlags.AI title="Anguilla" className={className} />,
        AL: <CountryFlags.AL title="Albania" className={className} />,
        AM: <CountryFlags.AM title="Armenia" className={className} />,
        AO: <CountryFlags.AO title="Angola" className={className} />,
        AQ: <CountryFlags.AQ title="Antarctica" className={className} />,
        AR: <CountryFlags.AR title="Argentina" className={className} />,
        AS: <CountryFlags.AS title="American Samoa" className={className} />,
        AT: <CountryFlags.AT title="Austria" className={className} />,
        AU: <CountryFlags.AU title="Australia" className={className} />,
        AW: <CountryFlags.AW title="Aruba" className={className} />,
        AX: <CountryFlags.AX title="Åland Islands" className={className} />,
        AZ: <CountryFlags.AZ title="Azerbaijan" className={className} />,
        BA: <CountryFlags.BA title="Bosnia and Herzegovina" className={className} />,
        BB: <CountryFlags.BB title="Barbados" className={className} />,
        BD: <CountryFlags.BD title="Bangladesh" className={className} />,
        BE: <CountryFlags.BE title="Belgium" className={className} />,
        BF: <CountryFlags.BF title="Burkina Faso" className={className} />,
        BG: <CountryFlags.BG title="Bulgaria" className={className} />,
        BH: <CountryFlags.BH title="Bahrain" className={className} />,
        BI: <CountryFlags.BI title="Burundi" className={className} />,
        BJ: <CountryFlags.BJ title="Benin" className={className} />,
        BL: <CountryFlags.BL title="Saint Barthélemy" className={className} />,
        BM: <CountryFlags.BM title="Bermuda" className={className} />,
        BN: <CountryFlags.BN title="Brunei" className={className} />,
        BO: <CountryFlags.BO title="Bolivia" className={className} />,
        BQ: <CountryFlags.BQ title="Caribbean Netherlands" className={className} />,
        BR: <CountryFlags.BR title="Brazil" className={className} />,
        BS: <CountryFlags.BS title="Bahamas" className={className} />,
        BT: <CountryFlags.BT title="Bhutan" className={className} />,
        BV: <CountryFlags.BV title="Bouvet Island" className={className} />,
        BW: <CountryFlags.BW title="Botswana" className={className} />,
        BY: <CountryFlags.BY title="Belarus" className={className} />,
        BZ: <CountryFlags.BZ title="Belize" className={className} />,
        CA: <CountryFlags.CA title="Canada" className={className} />,
        CC: <CountryFlags.CC title="Cocos (Keeling) Islands" className={className} />,
        CD: <CountryFlags.CD title="Congo (Kinshasa)" className={className} />,
        CF: <CountryFlags.CF title="Central African Republic" className={className} />,
        CG: <CountryFlags.CG title="Congo (Brazzaville)" className={className} />,
        CH: <CountryFlags.CH title="Switzerland" className={className} />,
        CI: <CountryFlags.CI title="Côte d'Ivoire" className={className} />,
        CK: <CountryFlags.CK title="Cook Islands" className={className} />,
        CL: <CountryFlags.CL title="Chile" className={className} />,
        CM: <CountryFlags.CM title="Cameroon" className={className} />,
        CN: <CountryFlags.CN title="China" className={className} />,
        CO: <CountryFlags.CO title="Colombia" className={className} />,
        CR: <CountryFlags.CR title="Costa Rica" className={className} />,
        CU: <CountryFlags.CU title="Cuba" className={className} />,
        CV: <CountryFlags.CV title="Cape Verde" className={className} />,
        CW: <CountryFlags.CW title="Curaçao" className={className} />,
        CX: <CountryFlags.CX title="Christmas Island" className={className} />,
        CY: <CountryFlags.CY title="Cyprus" className={className} />,
        CZ: <CountryFlags.CZ title="Czech Republic" className={className} />,
        DE: <CountryFlags.DE title="Germany" className={className} />,
        DJ: <CountryFlags.DJ title="Djibouti" className={className} />,
        DK: <CountryFlags.DK title="Denmark" className={className} />,
        DM: <CountryFlags.DM title="Dominica" className={className} />,
        DO: <CountryFlags.DO title="Dominican Republic" className={className} />,
        DZ: <CountryFlags.DZ title="Algeria" className={className} />,
        EC: <CountryFlags.EC title="Ecuador" className={className} />,
        EE: <CountryFlags.EE title="Estonia" className={className} />,
        EG: <CountryFlags.EG title="Egypt" className={className} />,
        EH: <CountryFlags.EH title="Western Sahara" className={className} />,
        ER: <CountryFlags.ER title="Eritrea" className={className} />,
        ES: <CountryFlags.ES title="Spain" className={className} />,
        ET: <CountryFlags.ET title="Ethiopia" className={className} />,
        EU: <CountryFlags.EU title="European Union" className={className} />,
        FI: <CountryFlags.FI title="Finland" className={className} />,
        FJ: <CountryFlags.FJ title="Fiji" className={className} />,
        FK: <CountryFlags.FK title="Falkland Islands" className={className} />,
        FM: <CountryFlags.FM title="Micronesia" className={className} />,
        FO: <CountryFlags.FO title="Faroe Islands" className={className} />,
        FR: <CountryFlags.FR title="France" className={className} />,
        GA: <CountryFlags.GA title="Gabon" className={className} />,
        GB: <CountryFlags.GB title="United Kingdom" className={className} />,
        GD: <CountryFlags.GD title="Grenada" className={className} />,
        GE: <CountryFlags.GE title="Georgia" className={className} />,
        GF: <CountryFlags.GF title="French Guiana" className={className} />,
        GG: <CountryFlags.GG title="Guernsey" className={className} />,
        GH: <CountryFlags.GH title="Ghana" className={className} />,
        GI: <CountryFlags.GI title="Gibraltar" className={className} />,
        GL: <CountryFlags.GL title="Greenland" className={className} />,
        GM: <CountryFlags.GM title="Gambia" className={className} />,
        GN: <CountryFlags.GN title="Guinea" className={className} />,
        GP: <CountryFlags.GP title="Guadeloupe" className={className} />,
        GQ: <CountryFlags.GQ title="Equatorial Guinea" className={className} />,
        GR: <CountryFlags.GR title="Greece" className={className} />,
        GS: <CountryFlags.GS title="South Georgia and the South Sandwich Islands" className={className} />,
        GT: <CountryFlags.GT title="Guatemala" className={className} />,
        GU: <CountryFlags.GU title="Guam" className={className} />,
        GW: <CountryFlags.GW title="Guinea-Bissau" className={className} />,
        GY: <CountryFlags.GY title="Guyana" className={className} />,
        HK: <CountryFlags.HK title="Hong Kong SAR China" className={className} />,
        HM: <CountryFlags.HM title="Heard & McDonald Islands" className={className} />,
        HN: <CountryFlags.HN title="Honduras" className={className} />,
        HR: <CountryFlags.HR title="Croatia" className={className} />,
        HT: <CountryFlags.HT title="Haiti" className={className} />,
        HU: <CountryFlags.HU title="Hungary" className={className} />,
        IC: <CountryFlags.IC title="Canary Islands" className={className} />,
        ID: <CountryFlags.ID title="Indonesia" className={className} />,
        IE: <CountryFlags.IE title="Ireland" className={className} />,
        IL: <CountryFlags.IL title="Israel" className={className} />,
        IM: <CountryFlags.IM title="Isle of Man" className={className} />,
        IN: <CountryFlags.IN title="India" className={className} />,
        IO: <CountryFlags.IO title="British Indian Ocean Territory" className={className} />,
        IQ: <CountryFlags.IQ title="Iraq" className={className} />,
        IR: <CountryFlags.IR title="Iran" className={className} />,
        IS: <CountryFlags.IS title="Iceland" className={className} />,
        IT: <CountryFlags.IT title="Italy" className={className} />,
        JE: <CountryFlags.JE title="Jersey" className={className} />,
        JM: <CountryFlags.JM title="Jamaica" className={className} />,
        JO: <CountryFlags.JO title="Jordan" className={className} />,
        JP: <CountryFlags.JP title="Japan" className={className} />,
        KE: <CountryFlags.KE title="Kenya" className={className} />,
        KG: <CountryFlags.KG title="Kyrgyzstan" className={className} />,
        KH: <CountryFlags.KH title="Cambodia" className={className} />,
        KI: <CountryFlags.KI title="Kiribati" className={className} />,
        KM: <CountryFlags.KM title="Comoros" className={className} />,
        KN: <CountryFlags.KN title="Saint Kitts and Nevis" className={className} />,
        KP: <CountryFlags.KP title="North Korea" className={className} />,
        KR: <CountryFlags.KR title="South Korea" className={className} />,
        KW: <CountryFlags.KW title="Kuwait" className={className} />,
        KY: <CountryFlags.KY title="Cayman Islands" className={className} />,
        KZ: <CountryFlags.KZ title="Kazakhstan" className={className} />,
        LA: <CountryFlags.LA title="Laos" className={className} />,
        LB: <CountryFlags.LB title="Lebanon" className={className} />,
        LC: <CountryFlags.LC title="Saint Lucia" className={className} />,
        LI: <CountryFlags.LI title="Liechtenstein" className={className} />,
        LK: <CountryFlags.LK title="Sri Lanka" className={className} />,
        LR: <CountryFlags.LR title="Liberia" className={className} />,
        LS: <CountryFlags.LS title="Lesotho" className={className} />,
        LT: <CountryFlags.LT title="Lithuania" className={className} />,
        LU: <CountryFlags.LU title="Luxembourg" className={className} />,
        LV: <CountryFlags.LV title="Latvia" className={className} />,
        LY: <CountryFlags.LY title="Libya" className={className} />,
        MA: <CountryFlags.MA title="Morocco" className={className} />,
        MC: <CountryFlags.MC title="Monaco" className={className} />,
        MD: <CountryFlags.MD title="Moldova" className={className} />,
        ME: <CountryFlags.ME title="Montenegro" className={className} />,
        MF: <CountryFlags.MF title="Saint Martin (French part)" className={className} />,
        MG: <CountryFlags.MG title="Madagascar" className={className} />,
        MH: <CountryFlags.MH title="Marshall Islands" className={className} />,
        MK: <CountryFlags.MK title="North Macedonia" className={className} />,
        ML: <CountryFlags.ML title="Mali" className={className} />,
        MM: <CountryFlags.MM title="Myanmar (Burma)" className={className} />,
        MN: <CountryFlags.MN title="Mongolia" className={className} />,
        MO: <CountryFlags.MO title="Macao SAR China" className={className} />,
        MP: <CountryFlags.MP title="Northern Mariana Islands" className={className} />,
        MQ: <CountryFlags.MQ title="Martinique" className={className} />,
        MR: <CountryFlags.MR title="Mauritania" className={className} />,
        MS: <CountryFlags.MS title="Montserrat" className={className} />,
        MT: <CountryFlags.MT title="Malta" className={className} />,
        MU: <CountryFlags.MU title="Mauritius" className={className} />,
        MV: <CountryFlags.MV title="Maldives" className={className} />,
        MW: <CountryFlags.MW title="Malawi" className={className} />,
        MX: <CountryFlags.MX title="Mexico" className={className} />,
        MY: <CountryFlags.MY title="Malaysia" className={className} />,
        MZ: <CountryFlags.MZ title="Mozambique" className={className} />,
        NA: <CountryFlags.NA title="Namibia" className={className} />,
        NC: <CountryFlags.NC title="New Caledonia" className={className} />,
        NE: <CountryFlags.NE title="Niger" className={className} />,
        NF: <CountryFlags.NF title="Norfolk Island" className={className} />,
        NG: <CountryFlags.NG title="Nigeria" className={className} />,
        NI: <CountryFlags.NI title="Nicaragua" className={className} />,
        NL: <CountryFlags.NL title="Netherlands" className={className} />,
        NO: <CountryFlags.NO title="Norway" className={className} />,
        NP: <CountryFlags.NP title="Nepal" className={className} />,
        NR: <CountryFlags.NR title="Nauru" className={className} />,
        NU: <CountryFlags.NU title="Niue" className={className} />,
        NZ: <CountryFlags.NZ title="New Zealand" className={className} />,
        OM: <CountryFlags.OM title="Oman" className={className} />,
        PA: <CountryFlags.PA title="Panama" className={className} />,
        PE: <CountryFlags.PE title="Peru" className={className} />,
        PF: <CountryFlags.PF title="French Polynesia" className={className} />,
        PG: <CountryFlags.PG title="Papua New Guinea" className={className} />,
        PH: <CountryFlags.PH title="Philippines" className={className} />,
        PK: <CountryFlags.PK title="Pakistan" className={className} />,
        PL: <CountryFlags.PL title="Poland" className={className} />,
        PM: <CountryFlags.PM title="Saint Pierre and Miquelon" className={className} />,
        PN: <CountryFlags.PN title="Pitcairn Islands" className={className} />,
        PR: <CountryFlags.PR title="Puerto Rico" className={className} />,
        PS: <CountryFlags.PS title="Palestinian Territories" className={className} />,
        PT: <CountryFlags.PT title="Portugal" className={className} />,
        PW: <CountryFlags.PW title="Palau" className={className} />,
        PY: <CountryFlags.PY title="Paraguay" className={className} />,
        QA: <CountryFlags.QA title="Qatar" className={className} />,
        RE: <CountryFlags.RE title="Réunion" className={className} />,
        RO: <CountryFlags.RO title="Romania" className={className} />,
        RS: <CountryFlags.RS title="Serbia" className={className} />,
        RU: <CountryFlags.RU title="Russia" className={className} />,
        RW: <CountryFlags.RW title="Rwanda" className={className} />,
        SA: <CountryFlags.SA title="Saudi Arabia" className={className} />,
        SB: <CountryFlags.SB title="Solomon Islands" className={className} />,
        SC: <CountryFlags.SC title="Seychelles" className={className} />,
        SD: <CountryFlags.SD title="Sudan" className={className} />,
        SE: <CountryFlags.SE title="Sweden" className={className} />,
        SG: <CountryFlags.SG title="Singapore" className={className} />,
        SH: <CountryFlags.SH title="Saint Helena" className={className} />,
        SI: <CountryFlags.SI title="Slovenia" className={className} />,
        SJ: <CountryFlags.SJ title="Svalbard and Jan Mayen" className={className} />,
        SK: <CountryFlags.SK title="Slovakia" className={className} />,
        SL: <CountryFlags.SL title="Sierra Leone" className={className} />,
        SM: <CountryFlags.SM title="San Marino" className={className} />,
        SN: <CountryFlags.SN title="Senegal" className={className} />,
        SO: <CountryFlags.SO title="Somalia" className={className} />,
        SR: <CountryFlags.SR title="Suriname" className={className} />,
        SS: <CountryFlags.SS title="South Sudan" className={className} />,
        ST: <CountryFlags.ST title="São Tomé and Príncipe" className={className} />,
        SV: <CountryFlags.SV title="El Salvador" className={className} />,
        SX: <CountryFlags.SX title="Sint Maarten" className={className} />,
        SY: <CountryFlags.SY title="Syria" className={className} />,
        SZ: <CountryFlags.SZ title="Eswatini" className={className} />,
        TA: <CountryFlags.TA title="Tristan da Cunha" className={className} />,
        TC: <CountryFlags.TC title="Turks and Caicos Islands" className={className} />,
        TD: <CountryFlags.TD title="Chad" className={className} />,
        TF: <CountryFlags.TF title="French Southern and Antarctic Lands" className={className} />,
        TG: <CountryFlags.TG title="Togo" className={className} />,
        TH: <CountryFlags.TH title="Thailand" className={className} />,
        TJ: <CountryFlags.TJ title="Tajikistan" className={className} />,
        TK: <CountryFlags.TK title="Tokelau" className={className} />,
        TL: <CountryFlags.TL title="Timor-Leste" className={className} />,
        TM: <CountryFlags.TM title="Turkmenistan" className={className} />,
        TN: <CountryFlags.TN title="Tunisia" className={className} />,
        TO: <CountryFlags.TO title="Tonga" className={className} />,
        TR: <CountryFlags.TR title="Turkey" className={className} />,
        TT: <CountryFlags.TT title="Trinidad and Tobago" className={className} />,
        TV: <CountryFlags.TV title="Tuvalu" className={className} />,
        TW: <CountryFlags.TW title="Taiwan" className={className} />,
        TZ: <CountryFlags.TZ title="Tanzania" className={className} />,
        UA: <CountryFlags.UA title="Ukraine" className={className} />,
        UG: <CountryFlags.UG title="Uganda" className={className} />,
        UM: <CountryFlags.UM title="U.S. Outlying Islands" className={className} />,
        US: <CountryFlags.US title="United States" className={className} />,
        UY: <CountryFlags.UY title="Uruguay" className={className} />,
        UZ: <CountryFlags.UZ title="Uzbekistan" className={className} />,
        VA: <CountryFlags.VA title="Vatican City" className={className} />,
        VC: <CountryFlags.VC title="Saint Vincent and the Grenadines" className={className} />,
        VE: <CountryFlags.VE title="Venezuela" className={className} />,
        VG: <CountryFlags.VG title="British Virgin Islands" className={className} />,
        VI: <CountryFlags.VI title="U.S. Virgin Islands" className={className} />,
        VN: <CountryFlags.VN title="Vietnam" className={className} />,
        VU: <CountryFlags.VU title="Vanuatu" className={className} />,
        WF: <CountryFlags.WF title="Wallis and Futuna" className={className} />,
        WS: <CountryFlags.WS title="Samoa" className={className} />,
        XK: <CountryFlags.XK title="Kosovo" className={className} />,
        YE: <CountryFlags.YE title="Yemen" className={className} />,
        YT: <CountryFlags.YT title="Mayotte" className={className} />,
        ZA: <CountryFlags.ZA title="South Africa" className={className} />,
        ZM: <CountryFlags.ZM title="Zambia" className={className} />,
        ZW: <CountryFlags.ZW title="Zimbabwe" className={className} />,
    };

    const flagComponent = countryFlagComponents[countryName];

    return !flagComponent ? <></> : (
        <div className="grid place-content-center w-5 h-5 rounded-full overflow-hidden">
            {flagComponent}
        </div>
    );
}